name: common-action
description: This is a common action that can be used by other actions

inputs:
  build:
    description: 'If we need to build the project'
    required: true
    default: 'false'

runs: 
  using: composite
  steps:
      - run: npm ci --force
        shell: bash
      - run: npm run build
        shell: bash
        if: ${{ inputs.build == 'true' }}
      - run: npm run test
        shell: bash