name: common-action
description: This is a common action that can be used by other actions

runs: 
  using: composite
  steps:
      - run: npm ci
        shell: bash
      - run: npm run build
        shell: bash
      - run: npm run test
        shell: bash