name : build-workflow

on : 
    push:
        branches:
        - main

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
           node-version: 16
           cache: 'npm'
        - run: npm ci

    build:
        runs-on: ubuntu-latest
        needs: setup
        steps:
        - name: npm run build
          run: |
            npm run build