name : build-workflow

on : 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

    
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [16.x,18.x]
        steps:
        - uses: actions/checkout@v3
        - name : Setup Npm
          uses: actions/setup-node@v3
          with:
           node-version: ${{matrix.node}}
           cache: 'npm'
        - name: Install node modules
          run: npm ci --force
        - name: Run build
          run: npm run build
    