name : build-workflow

on : 
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name : npm install
          uses: actions/setup-node@v3
          with:
           node-version: 16
           cache: 'npm'
        - name: npm ci
          run: npm ci --force
        - name: npm run build
          run: npm run build
    