# name of your workflow
name : build-workflow

# define events that trigger the workflow
on : 
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

# define jobs that run in the workflow
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        # checkout the repository
        - uses: actions/checkout@v3
        # setup node with node version 16.x
        - name : Setup Npm
          uses: actions/setup-node@v3
          with:
           node-version: '18.x'
           cache: 'npm'
        # Install node modules
        - name: Install node modules
          run: npm ci --force
        # Run build script
        - name: Run build
          run: npm run build
    