name: Reusable workflow

on: 
  workflow_dispatch:
    inputs:
        workflow_name:
            description: Workflow description
            type: string
            required: true
        
        node_version:
            description: Node version
            type: string
            required: true
            
  workflow_call:
    inputs:
        workflow_name:
            description: Workflow description
            type: string
            default: Dispatch workflow

        node_version:
            description: Node version
            type: string
            default: 16.x
         
jobs:
    Run_Build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:  ${{ inputs.node_version }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup NodeJs
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node }}
          - name: Install node modules
            run: npm ci --force
          - name: Run Build
            run: npm run build

