name: Reusable workflow

on: 
  workflow_dispatch:
    inputs:
        workflow_name:
            description: Workflow description
            required: true
            default: 'Workflow name'
                
        node_versions: 
            description: Node matrix
            required: true
            default: '16.x'
            
jobs:
    Run_Build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:  ${{ fromJson(inputs.node_versions) }} 
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup NodeJs
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node }}git a
          - name: Install node modules
            run: npm ci --force
          - name: Run Build
            run: npm run build

