name: Reusable workflow

on: 
  # workflow_dispatch:
  #   inputs:
  #       workflow_name:
  #           description: Workflow description
  #           type: string
  #           required: true
        
  #       build:
  #           description: Node version
  #           type: boolean
  #           required: true

  #       test:
  #           description: Projects to run
  #           type: boolean
  #           required: true
        
  #       projects:
  #           description: Projects to run
  #           type: string
  #           required: true
            
  workflow_call:
    inputs:
        workflow_name:
            description: Workflow description
            type: string
            default: Dispatch workflow

        build:
            description: Node version
            type: boolean
            default: true

        test:
            description: Projects to run
            type: boolean
            default: false

        projects:
            description: Projects to run
            type: string
            default: router-app
         
jobs:
    Run_Build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:  [16.x,18.x]
                projects:  ${{ fromJSON(inputs.projects) }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup NodeJs
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node }}
          - name: Install node modules
            run: npm ci --force
          - name: Run Build
            if: inputs.build
            run: npm run build --project= ${{ matrix.projects }}
          - name: Run Test
            if: inputs.test
            run: npm run test --project= ${{ matrix.projects }}


