name: Reusable workflow

on: 
  workflow_dispatch:
    inputs:
        workflow_name: 
                description: Workflow description
                required: true
                default: 'Workflow name'

        node_matrix: 
            description: 'Node matrix'
            required: true
            default: '16.x'
            
            
jobs:
    node_matrix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node:  ${{ fromJson(inputs.node_matrix) }} 
        steps:
        - uses: actions/checkout@v2
        - name: Setup NodeJs
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install node modules
          run: npm ci --force
        - name: Run Build
          run: npm run build

