name: Use Reusabel workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    Run_Workflow:
                name: resuse
                uses : ./.github/workflows/reusable.yml
                with:
                    workflow_name: "Release Workflow"
                    node_matrix:  16.x,18.x

