name: Use Reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    RunWorkflow:
        name: ReUse workflow
        uses: ./.github/workflows/reusable.yml
        with:
          workflow_name: Release Workflow
          node_version: 18.x