name : test-workflow

on :
#   push :
#     branches :
#       - master
    workflow_dispatch :
        inputs :
            name :
                description : 'Person to greet'
                required : true
                default : 'Mona the Octocat'

jobs :
    approval:
        environment: staging
        runs-on : ubuntu-latest
        steps :
           - run : echo "Hello ${{ inputs.name }}"
           - run : echo "Deployment Approved by ${{ inputs.name }}"